spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url : YOUR JDBC URL
    username: USERNAME
    password: PASSWORD
  jpa:
    show-sql: true
  #此配置可以使得返回数据如果为null的话自动清空
  jackson:
    default-property-inclusion: non_null
  redis:
    host: HOST
    port: PORT
server:
  context-path: PATH
